title: Efe Oroh
logo: /images/headshot.png
description: Data Analytics | BI Dashboards | Automation | Applied Economics <br><br> Contact: <a href="mailto:EfeogheneOroh@gmail.com">EfeogheneOroh@gmail.com</a>
theme: jekyll-theme-minimal
